P127_Pronia/Models/Plant.cs
using Microsoft.AspNetCore.Http;
using P127_Pronia.Models.Base;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace P127_Pronia.Models
{
    public class Plant:BaseEntity
    {
        public string Name { get; set; }
        //[Column(TypeName ="decimal(6,2)")]
        public decimal Price { get; set; }
        public string Desc { get; set; }
        public string SKU { get; set; }
        public int PlantInformationId { get; set; }
        public PlantInformation PlantInformation { get; set; }
        public List<PlantImage> PlantImages { get; set; }
        public List<PlantCategory> PlantCategories { get; set; }

        [NotMapped]
        public List<int> CategoryIds { get; set; }


        [NotMapped]
        public IFormFile MainPhoto { get; set; }
        [NotMapped]
        public IFormFile HoverPhoto { get; set; }
        [NotMapped]
        public List<IFormFile> Photos { get; set; }
        [NotMapped]
        public List<int> ImagesId { get; set; }
    }
}

P127_Pronia/Areas/ProniaAdmin/Controllers/PlantController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using P127_Pronia.DAL;
using P127_Pronia.Models;
using P127_Pronia.Utilities;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace P127_Pronia.Areas.ProniaAdmin.Controllers
{
    [Area("ProniaAdmin")]
    [Authorize(Roles ="Moderator,Admin")]
    public class PlantController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _env;

        public PlantController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            List<Plant> model = _context.Plants
                .Include(p => p.PlantInformation)
                .Include(p => p.PlantCategories).ThenInclude(pc => pc.Category)
                .Include(p => p.PlantImages).ToList();
            return View(model);
        }

        public IActionResult Create()
        {
            ViewBag.Information = _context.PlantInformations.ToList();
            ViewBag.Categories = _context.Categories.ToList();
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create(Plant plant)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Information = _context.PlantInformations.ToList();
                ViewBag.Categories = _context.Categories.ToList();
                return View();
            }
            if (plant.MainPhoto == null || plant.HoverPhoto == null || plant.Photos == null)
            {

                ViewBag.Information = _context.PlantInformations.ToList();
                ViewBag.Categories = _context.Categories.ToList();
                ModelState.AddModelError(string.Empty, "You must choose 1 main photo and 1 hover photo and 1 another photo");
                return View();
            }

            if (!plant.MainPhoto.ImageIsOkay(2) || !plant.HoverPhoto.ImageIsOkay(2))
            {
                ViewBag.Information = _context.PlantInformations.ToList();
                ViewBag.Categories = _context.Categories.ToList();
                ModelState.AddModelError(string.Empty, "Please choose valid image file");
                return View();
            }

            plant.PlantImages = new List<PlantImage>();
            TempData["FileName"] = "";
            List<IFormFile> removeable = new List<IFormFile>();
            foreach (var photo in plant.Photos.ToList())
            {
                if (!photo.ImageIsOkay(2))
                {
                    removeable.Add(photo);
                    TempData["FileName"] += photo.FileName + ",";
                    continue;
                }
                PlantImage another = new PlantImage
                {
                    Name = await photo.FileCreate(_env.WebRootPath, "assets/images/website-images"),
                    IsMain = false,
                    Alternative = photo.Name,
                    Plant = plant
                };
                plant.PlantImages.Add(another);
            }

            plant.Photos.RemoveAll(p=>removeable.Any(r=>r.FileName == p.FileName));

            PlantImage main = new PlantImage
            {
                Name = await plant.MainPhoto.FileCreate(_env.WebRootPath, "assets/images/website-images"),
                IsMain = true,
                Alternative = plant.Name,
                Plant = plant
            };
            PlantImage hover = new PlantImage
            {
                Name = await plant.HoverPhoto.FileCreate(_env.WebRootPath, "assets/images/website-images"),
                IsMain = null,
                Alternative = plant.Name,
                Plant = plant
            };

            plant.PlantImages.Add(main);
            plant.PlantImages.Add(hover);

            plant.PlantCategories = new List<PlantCategory>();
            foreach (int id in plant.CategoryIds)
            {
                PlantCategory category = new PlantCategory
                {
                    CategoryId = id,
                    Plant = plant
                };
                plant.PlantCategories.Add(category);
            }

            await _context.Plants.AddAsync(plant);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        
        public async Task<IActionResult> Update(int? id)
        {
            ViewBag.Information = _context.PlantInformations.ToList();
            ViewBag.Categories = _context.Categories.ToList();
            if (id is null || id == 0) return NotFound();
            Plant plant = await _context.Plants
                .Include(p=>p.PlantImages)
                .Include(p => p.PlantInformation)
                .Include(p => p.PlantCategories)
                .ThenInclude(p => p.Category).SingleOrDefaultAsync(p=>p.Id == id);
            if (plant == null) return NotFound();
            return View(plant);
        }


        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [ActionName("Update")]
        public async Task<IActionResult> Edit(int? id, Plant plant)
        {
            if (id is null || id == 0) return NotFound();
            Plant existed = await _context.Plants
                .Include(p => p.PlantImages)
                .Include(p => p.PlantInformation)
                .Include(p => p.PlantCategories)
                .ThenInclude(p => p.Category).SingleOrDefaultAsync(p => p.Id == id);
            if (existed == null) return NotFound();

            List<PlantImage> removeable = existed.PlantImages.Where(p => p.IsMain == false && !plant.ImagesId.Contains(p.Id)).ToList();
            existed.PlantImages.RemoveAll(p => removeable.Any(r => p.Id == r.Id));

            return Json(existed.PlantImages);
        }
    }
}

P127_Pronia/Controllers/PlantController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using P127_Pronia.DAL;
using P127_Pronia.Models;
using P127_Pronia.ViewModels;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace P127_Pronia.Controllers
{
    public class PlantController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public PlantController(ApplicationDbContext context,UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public async Task<IActionResult> Detail(int? id)
        {
            if (id is null || id == 0)
            {
                return NotFound();
            }
            Plant plant = await _context.Plants.Include(p => p.PlantImages)
                .Include(p => p.PlantInformation).Include(p => p.PlantCategories).ThenInclude(p => p.Category)
                .FirstOrDefaultAsync(p => p.Id == id);

            ViewBag.Plants = await _context.Plants.Include(p => p.PlantImages).ToListAsync();
            if (plant is null) return NotFound();
            return View(plant);
        }

        public async Task<IActionResult> Partial()
        {
            List<Plant> plants = await _context.Plants.Include(p => p.PlantImages).ToListAsync();

            return PartialView("_PlantsPartialView", plants);

        }

        public async Task<IActionResult> AddBasket(int? id)
        {
            if (id is null || id == 0) return NotFound();

            Plant plant = await _context.Plants.FirstOrDefaultAsync(p => p.Id == id);
            if (plant == null) return NotFound();
            if (User.Identity.IsAuthenticated && User.IsInRole("Member"))
            {
                AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);
                if (user == null) return NotFound();
                BasketItem existed = await _context.BasketItems.FirstOrDefaultAsync(b => b.AppUserId == user.Id && b.PlantId == plant.Id);
                if(existed == null)
                {
                    existed = new BasketItem
                    {
                        Plant = plant,
                        AppUser = user,
                        Quantity = 1,
                        Price = plant.Price
                    };
                    _context.BasketItems.Add(existed);
                }
                else
                {
                    existed.Quantity++;
                }
                await _context.SaveChangesAsync();
            }
            else
            {
                string basketStr = HttpContext.Request.Cookies["Basket"];

                BasketVM basket;

                if (string.IsNullOrEmpty(basketStr))
                {
                    basket = new BasketVM();
                    BasketCookieItemVM cookieItem = new BasketCookieItemVM
                    {
                        Id = plant.Id,
                        Quantity = 1
                    };
                    basket.BasketCookieItemVMs = new List<BasketCookieItemVM>();
                    basket.BasketCookieItemVMs.Add(cookieItem);
                    basket.TotalPrice = plant.Price;

                }
                else
                {
                    basket = JsonConvert.DeserializeObject<BasketVM>(basketStr);
                    BasketCookieItemVM existed = basket.BasketCookieItemVMs.Find(p => p.Id == id);
                    if (existed == null)
                    {
                        BasketCookieItemVM cookieItem = new BasketCookieItemVM
                        {
                            Id = plant.Id,
                            Quantity = 1
                        };
                        basket.BasketCookieItemVMs.Add(cookieItem);
                        basket.TotalPrice += plant.Price;
                    }
                    else
                    {
                        basket.TotalPrice += plant.Price;
                        existed.Quantity++;
                    }
                }
                basketStr = JsonConvert.SerializeObject(basket);

                HttpContext.Response.Cookies.Append("Basket", basketStr);
            }

            return RedirectToAction("Index", "Home");
        }



        public IActionResult ShowBasket()
        {
            if (HttpContext.Request.Cookies["Basket"] == null) return NotFound();
            BasketVM basket = JsonConvert.DeserializeObject<BasketVM>(HttpContext.Request.Cookies["Basket"]);
            return Json(basket);
        }
    }
}

P127_Pronia/Areas/ProniaAdmin/Views/Plant/Create.cshtml
@model Plant
@{
    ViewData["Title"] = "Create";
}


<div class="main-panel">
    <h1>Create slider</h1>
    <div class="alert alert-danger" asp-validation-summary="ModelOnly"></div>
    <form class="mt-3" method="post" enctype="multipart/form-data">
         <div>
        <label >Main:</label><br />
        <input asp-for="MainPhoto" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="MainPhoto"></span>
    </div>
     <div>
        <label >Hover:</label><br />
        <input asp-for="HoverPhoto" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="HoverPhoto"></span>
    </div>
    <div>
        <label >Images:</label><br />
        <input asp-for="Photos" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Photos"></span>
    </div>
    <div>
        <label >Name:</label><br />
        <input asp-for="Name" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div>
        <label >Price:</label><br />
        <input asp-for="Price" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Price"></span>
    </div>
    <div>
        <label >Description:</label><br />
        <input asp-for="Desc" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Desc"></span>
    </div>
    <div>
        <label >SKU:</label><br />
        <input asp-for="SKU" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="SKU"></span>
    </div>
    <div>
        <label >Plant Information:</label><br />
        <select class="form-control" asp-for="PlantInformationId" asp-items="@(new SelectList(ViewBag.Information,"Id","Shipping"))"></select>
    </div>
     <div>
        <label >Plant Categories:</label><br />
        <select class="form-control" asp-for="CategoryIds" asp-items="@(new SelectList(ViewBag.Categories,"Id","Name"))"></select>
    </div>
    <div class="mt-2">
        <button class="btn btn-success" type="submit">Create</button>
    </div>
</form>
</div>

P127_Pronia/Areas/ProniaAdmin/Views/Plant/Index.cshtml
@model List<Plant>
@{
    ViewData["Title"] = "Index";
}




<div class="main-panel">
    <div>
        <a class="btn btn-success" asp-area="ProniaAdmin" asp-controller="Plant" asp-action="Create">Create new plant</a>
    </div>
    @if(TempData["FileName"] != null)
    {
        <div class="alert alert-danger">@TempData["FileName"] files could not upload</div>
    }
    <div class="table-responsive pt-3">
        <table class="table table-dark">
            <thead>
                <tr>
                    <th>
                        Image
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
                        SKU
                    </th>
                    <th>
                        Settings
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (Plant plant in Model)
                {
                    <tr>
                        <td>
                            <img style="width:150px !important; height:150px; object-fit:contain" src="~/assets/images/website-images/@plant.PlantImages.FirstOrDefault(p=>p.IsMain == true)?.Name" alt="">
                        </td>
                        <td>
                            @plant.Name
                        </td>
                         <td>
                            @plant.Price
                        </td>
                        <td>
                            @plant.SKU
                        </td>
                        <td  class="d-flex">
                                <div>
                                    <a asp-area="ProniaAdmin" asp-controller="plant" asp-action="Update" asp-route-id="@plant.Id" class="btn btn-warning"><i class="mdi mdi-border-color"></i></a>
                                </div>
                                <div>
                                    <a class="btn btn-danger" asp-area="ProniaAdmin" asp-controller="plant" asp-action="Delete" asp-route-id="@plant.Id"><i class="mdi mdi-delete"></i></a>
                                </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

P127_Pronia/Areas/ProniaAdmin/Views/Plant/Update.cshtml
@model Plant
@{
    ViewData["Title"] = "Update";
}


<div class="main-panel">
    <h1>Create slider</h1>
    <div class="alert alert-danger" asp-validation-summary="ModelOnly"></div>
    <form class="mt-3" method="post" enctype="multipart/form-data" >
        <div>
            <label>Main:</label><br />
            <input asp-for="MainPhoto" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="MainPhoto"></span>
        </div>
        <div>
            <label>Hover:</label><br />
            <input asp-for="HoverPhoto" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="HoverPhoto"></span>
        </div>
        <div>
            <label>Images:</label><br />
            <input asp-for="Photos" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Photos"></span>
        </div>
        <div class="images">
            <div class="image">
                <h2>Main</h2>
                <img src="~/assets/images/website-images/@Model.PlantImages.FirstOrDefault(p=>p.IsMain == true).Name">
            </div>
            <div class="image">
                <h2>Hover</h2>
                <img src="~/assets/images/website-images/@Model.PlantImages.FirstOrDefault(p=>p.IsMain == null)?.Name">
            </div>
            <h2>Another images</h2>
            <div class="image d-flex">

                @foreach (PlantImage image in Model.PlantImages.Where(p => p.IsMain == false))
                {
                    <div style="position:relative;" class="col-sm-3">
                        <img src="~/assets/images/website-images/@image.Name" style="width:100%;height:200px;object-fit:contain">
                        <input type="hidden" name="ImagesId" value="@image.Id">
                        <button style="position:absolute; right:5px" type="button" class="btn btn-danger">X</button>
                    </div>
                }
            </div>
        </div>
        <div>
            <label>Name:</label><br />
            <input asp-for="Name" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
        <div>
            <label>Price:</label><br />
            <input asp-for="Price" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Price"></span>
        </div>
        <div>
            <label>Description:</label><br />
            <input asp-for="Desc" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Desc"></span>
        </div>
        <div>
            <label>SKU:</label><br />
            <input asp-for="SKU" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="SKU"></span>
        </div>
        <div>
            <label>Plant Information:</label><br />
            <select class="form-control" asp-for="PlantInformationId" asp-items="@(new SelectList(ViewBag.Information,"Id","Shipping"))"></select>
        </div>
        <div>
            <label>Plant Categories:</label><br />
            @*<select class="form-control" asp-for="CategoryIds" asp-items="@(new SelectList(ViewBag.Categories,"Id","Name"))"></select>*@
            <select class="form-control" asp-for="CategoryIds">
                @foreach (Category category in ViewBag.Categories)
                {
                    if (Model.PlantCategories.Exists(p => p.CategoryId == category.Id))
                    {
                        <option value="@category.Id" selected>@category.Name</option>
                    }
                    else
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                }
            </select>
        </div>
        <div class="mt-2">
            <button class="btn btn-success" type="submit">Create</button>
        </div>
    </form>
</div>


@section Scripts{
    <script>
        let btns = document.querySelectorAll(".btn-danger")

        btns.forEach(b => {
            b.addEventListener("click", function() {
                b.parentElement.remove();
            })
        })
    </script>
}